In [1]:
import pandas as pd
import numpy as np

bc = pd.read_csv('Downloads/wdbc.data', header = None)
bc.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [2]:
#I just looked up what are the column names supposed to be for this
columns = ['ID', 'Diagnosis','radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean','compactness_mean', 'concavity_mean', 'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean','radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se','compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se', 'fractal_dimension_se','radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst','compactness_worst', 'concavity_worst', 'concave_points_worst', 'symmetry_worst', 'fractal_dimension_worst']
bc.columns = columns
bc.head()

,ID,Diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
from sklearn.model_selection import train_test_split

bc = bc.drop('ID', axis = 1) #I don't want it reading into ID as a number to compute
bc['Diagnosis'] = bc['Diagnosis'].map({'M': 1, 'B': 0})

X = bc.drop('Diagnosis', axis = 1)
y = bc['Diagnosis']

#Train test split 80-20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [18]:
#Train the decision tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

grid_decide = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [1, 2, 3, 4, 5, 6]
}

decide = DecisionTreeClassifier(random_state=42)

grid_search_decide = GridSearchCV(estimator = decide, param_grid = grid_decide, cv = 5, scoring = 'accuracy')
grid_search_decide.fit(X_train, y_train)

print("Best Params:", grid_search_decide.best_params_)

best_decide = grid_search_decide.best_estimator_
y_pred_decide = best_decide.predict(X_test)
decide_accuracy = accuracy_score(y_test, y_pred_decide)

print("Decision Tree Accuracy:", decide_accuracy)

Best Params: {'criterion': 'entropy', 'max_depth': 3}
Decision Tree Accuracy: 0.9649122807017544

In [6]:
#Try with random forest

from sklearn.ensemble import RandomForestClassifier

#Differences in parameters: Random forest includes a parameter for number of estimators; this allows for control of how many 
#- trees to make the prediction off of. It also has by default Bootstrap = True, which allows for resampling over the course of
#- making all the trees. These are characteristics of ensemble learning (many trees) which is why only RandomForest has these
#- (Decision classifier is just 1 classifier).

In [22]:
from sklearn.model_selection import GridSearchCV

grid_forest = {
    'max_depth': [1, 2, 3, 4, 5],
    'criterion': ['gini', 'entropy'],
    'n_estimators': [10, 50, 100],
    'oob_score': [True],
    'bootstrap': [True]
}

forest = RandomForestClassifier(random_state = 42)

grid_search_forest = GridSearchCV(estimator = forest, param_grid = grid_forest, cv = 5, scoring = 'accuracy')
grid_search_forest.fit(X_train, y_train)

print("Best Params:", grid_search_forest.best_params_)

#Compare best forest to boost and decision classifier

best_forest = grid_search_forest.best_estimator_
y_pred_forest = best_forest.predict(X_test)
forest_accuracy = accuracy_score(y_test, y_pred_forest)

print("Random Forest Accuracy:", forest_accuracy)

Best Params: {'bootstrap': True, 'criterion': 'entropy', 'max_depth': 5, 'n_estimators': 100, 'oob_score': True}
Random Forest Accuracy: 0.9649122807017544

In [21]:
#decision tree already made, so..

print("Decision Tree Accuracy:", decide_accuracy)

Decision Tree Accuracy: 0.9649122807017544

In [11]:
#AdaBoost

from sklearn.ensemble import AdaBoostClassifier

In [20]:
boost = AdaBoostClassifier(estimator = best_decide, n_estimators=100, random_state=42)
boost.fit(X_train, y_train)
boost_accuracy = accuracy_score(y_test, boost.predict(X_test))

print("AdaBoost Accuracy:", boost_accuracy)

AdaBoost Accuracy: 0.9736842105263158

In [ ]:
#Decision tree and forest accuracies are exactly the same (?!??!?!). Adaboost is a little better.

In [ ]:
#AdaBoost, gradient boost and XGboost are used based on increasing complexity of the data set. AdaBoost uses decision stumps
#- and focuses on emphasizing misclassified samples, without using regularization. Stumps are considered "weak learners"
#- due to their small depth and are prone to overemphasizing noise or outliers that may not actually be super important,
#- causing overfitting. However, it is easy to use for simple data.

#Gradient boosting uses whole trees and stepwise descent rather than binary emphasis of misclassified points, making it more
#- complex and accurate of a boosting mechanism. These usually include hyperparameters that require finer tuning or custom loss functions,
#- though. The added complexity also makes it not as interpretable.

#On the other extreme is XGBoost, which is a highly specialized form of gradient boosting that fully supports all regularization
#- and handles missing values and parallelization itself. However, it requires even more hyperparameter tuning and takes an even
#- higher toll on interpretability. It is also the most resource intensive. It is despite this the fastest, most robust,
#- and most accurate boosting method capable of handling the most complex models. It might fall in performance if given raw
#- data e.g. images, like in HW2 comparing the different model fitting and feature extraction methods.